site_name: Лабораторные работы

theme:
  name: mkdocs

nav:
  - Главная: index.md
  - Лабораторная работа №1: Lab1/index.md
  - Лабораторная работа №2: Lab2/index.md


markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite